### ISSUE TITLE
Rename script to `git-addignore`

### ISSUE THREAD

**Issue by WorldSEnder** [TejasQ/add-gitignore#3]
Renaming the script to `git-addignore` (from `add-gitignore`) would allow the automatic git command discovery to kick in and let me type `git addignore` (notice no dash) to execute the command, aswell as (if you were to add them) help pages, etc... As a side effect, this is the standard for git utilities.

For example, `git` autocorrects mistyped command names. So if I'd mistakenly type `git addignroe`, git will propose `addignore` as the most similar command.

EDIT: `addignore` is just a proposal. As long as you keep the `git-` prefix, git will pick up on it, as long as the executable is in the path. Other possible names: `git-ignore` (sounds like an editor as a whole), or maybe `git-initignore`

**Comment by TejasQ** [comment]
Hi, @WorldSEnder! Thanks so much for contribution! 

Unfortunately, people already use this command quite a bit so we can't break the script name. We _can_, however, add an alias to it.

Would you like to submit a PR that does so?
